/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.Fork;
import Logica.Philosophers;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author gerar
 */
public class PhilosophersVisual extends javax.swing.JFrame {

    /**
     * Creates new form PhilosophersVisual
     */
    public PhilosophersVisual() {
        initComponents();
        this.Food1.setVisible(false);
        this.Food2.setVisible(false);
        this.Food3.setVisible(false);
        this.Food4.setVisible(false);
        this.Food5.setVisible(false);
        
        this.philoT1.setVisible(false);
        this.philoT2.setVisible(false);
        this.philoT3.setVisible(false);
        this.philoT4.setVisible(false);
        this.philoT5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        RFork1Philo = new javax.swing.JLabel();
        LFork1Philo = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtPhilo1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        RFork2Philo = new javax.swing.JLabel();
        LFork2Philo = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtPhilo2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        RFork3Philo = new javax.swing.JLabel();
        LFork3Philo = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtPhilo3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        RFork4Philo = new javax.swing.JLabel();
        LFork4Philo = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtPhilo4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        RFork5Philo = new javax.swing.JLabel();
        LFork5Philo = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtPhilo5 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        Food4 = new javax.swing.JLabel();
        Food5 = new javax.swing.JLabel();
        Food1 = new javax.swing.JLabel();
        Food2 = new javax.swing.JLabel();
        Food3 = new javax.swing.JLabel();
        philoT5 = new javax.swing.JLabel();
        philoT4 = new javax.swing.JLabel();
        philoT3 = new javax.swing.JLabel();
        philo3 = new javax.swing.JLabel();
        philo4 = new javax.swing.JLabel();
        philo5 = new javax.swing.JLabel();
        philo1 = new javax.swing.JLabel();
        philo2 = new javax.swing.JLabel();
        Fork4 = new javax.swing.JLabel();
        Fork3 = new javax.swing.JLabel();
        Fork1 = new javax.swing.JLabel();
        Fork2 = new javax.swing.JLabel();
        Fork5 = new javax.swing.JLabel();
        philoT1 = new javax.swing.JLabel();
        philoT2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        RFork1Philo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TenedorMasGrande.jpg"))); // NOI18N
        RFork1Philo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LFork1Philo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TenedorMasGrande.jpg"))); // NOI18N
        LFork1Philo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(RFork1Philo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LFork1Philo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RFork1Philo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LFork1Philo, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jLabel27.setText("R-Fork");

        jLabel28.setText("L-Fork");

        txtPhilo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhilo1.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(19, 19, 19))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(txtPhilo1)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(txtPhilo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Platon.jpg"))); // NOI18N
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 120));

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Socrates.jpg"))); // NOI18N

        RFork2Philo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TenedorMasGrande.jpg"))); // NOI18N
        RFork2Philo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LFork2Philo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TenedorMasGrande.jpg"))); // NOI18N
        LFork2Philo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(RFork2Philo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LFork2Philo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RFork2Philo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LFork2Philo, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jLabel29.setText("R-Fork");

        jLabel30.setText("L-Fork");

        txtPhilo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhilo2.setEnabled(false);
        txtPhilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhilo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(txtPhilo2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtPhilo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel11, java.awt.BorderLayout.PAGE_END);

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Aristoteles.jpg"))); // NOI18N

        RFork3Philo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TenedorMasGrande.jpg"))); // NOI18N
        RFork3Philo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LFork3Philo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TenedorMasGrande.jpg"))); // NOI18N
        LFork3Philo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(RFork3Philo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(LFork3Philo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RFork3Philo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LFork3Philo, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jLabel31.setText("R-Fork");

        jLabel32.setText("L-Fork");

        txtPhilo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhilo3.setEnabled(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel31)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel32))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtPhilo3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtPhilo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel19, java.awt.BorderLayout.PAGE_END);

        jPanel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mileto.jpg"))); // NOI18N
        jPanel20.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 162, 120));

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RFork4Philo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TenedorMasGrande.jpg"))); // NOI18N
        RFork4Philo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.add(RFork4Philo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        LFork4Philo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TenedorMasGrande.jpg"))); // NOI18N
        LFork4Philo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.add(LFork4Philo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, -1));

        jPanel20.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 160, 60));

        jLabel33.setText("R-Fork");
        jPanel20.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel34.setText("L-Fork");
        jPanel20.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        txtPhilo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhilo4.setEnabled(false);
        jPanel20.add(txtPhilo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, -1));

        jPanel5.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Heraclitus.jpg"))); // NOI18N
        jPanel15.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, 120));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, -1, -1));

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RFork5Philo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TenedorMasGrande.jpg"))); // NOI18N
        RFork5Philo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel24.add(RFork5Philo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, -1));

        LFork5Philo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TenedorMasGrande.jpg"))); // NOI18N
        LFork5Philo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel24.add(LFork5Philo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 76, -1));

        jPanel15.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 60));

        jLabel35.setText("R-Fork");
        jPanel15.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel36.setText("L-Fork");
        jPanel15.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        txtPhilo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhilo5.setEnabled(false);
        jPanel15.add(txtPhilo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 150, -1));

        jPanel6.add(jPanel15, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 810, 230));

        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciar)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 330, 350));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Food4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ComidaChida.jpg"))); // NOI18N
        jPanel18.add(Food4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        Food5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ComidaChida.jpg"))); // NOI18N
        jPanel18.add(Food5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        Food1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ComidaChida.jpg"))); // NOI18N
        jPanel18.add(Food1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        Food2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ComidaChida.jpg"))); // NOI18N
        jPanel18.add(Food2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        Food3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ComidaChida.jpg"))); // NOI18N
        jPanel18.add(Food3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        philoT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thougth.png"))); // NOI18N
        jPanel18.add(philoT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        philoT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thougth.png"))); // NOI18N
        jPanel18.add(philoT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        philoT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thougth.png"))); // NOI18N
        jPanel18.add(philoT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        philo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MiletoChiquito.jpg"))); // NOI18N
        jPanel18.add(philo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        philo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PlatonChiquito.jpg"))); // NOI18N
        jPanel18.add(philo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        philo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SocratesChiquito.jpg"))); // NOI18N
        jPanel18.add(philo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        philo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AristotelesChiquito.jpg"))); // NOI18N
        jPanel18.add(philo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        philo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HeraclitusChiquito.jpg"))); // NOI18N
        jPanel18.add(philo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        Fork4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tenedor.jpg"))); // NOI18N
        jPanel18.add(Fork4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        Fork3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tenedor.jpg"))); // NOI18N
        jPanel18.add(Fork3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        Fork1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tenedor.jpg"))); // NOI18N
        jPanel18.add(Fork1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        Fork2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tenedor.jpg"))); // NOI18N
        jPanel18.add(Fork2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        Fork5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tenedor.jpg"))); // NOI18N
        jPanel18.add(Fork5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        philoT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thougth.png"))); // NOI18N
        jPanel18.add(philoT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        philoT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thougth.png"))); // NOI18N
        jPanel18.add(philoT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MesaChida.jpg"))); // NOI18N
        jPanel18.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 220, 220));

        getContentPane().add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        Philosophers[] philosopher = new Philosophers[5];
//        Object[] forks = new Object[philosopher.length];
        JLabel[] philos = new JLabel[5];
        JLabel[] forks = new JLabel[5];
        Fork[] forkClass = new Fork[5];
        JLabel[] food = new JLabel[5];
        JLabel[] thoughts = new JLabel[5];
        JLabel[] forkImages = new JLabel[10];
        JTextField[] philoActions = new JTextField[5];           
        
        forks[0] = this.Fork1;
        forks[1] = this.Fork2;
        forks[2] = this.Fork3;
        forks[3] = this.Fork4;
        forks[4] = this.Fork5;
        
        Fork fork1 = new Fork();
        Fork fork2 = new Fork();
        Fork fork3 = new Fork();
        Fork fork4 = new Fork();
        Fork fork5 = new Fork();    
        
        forkClass[0] = fork1;
        forkClass[1] = fork2;
        forkClass[2] = fork3;
        forkClass[3] = fork4;
        forkClass[4] = fork5;
        
        food[0] = this.Food1;
        food[1] = this.Food2;
        food[2] = this.Food3;
        food[3] = this.Food4;
        food[4] = this.Food5;
        
        thoughts[0] =this.philoT1;
        thoughts[1] =this.philoT2;
        thoughts[2] =this.philoT3;
        thoughts[3] =this.philoT4;
        thoughts[4] =this.philoT5;
        
        forkImages[0] = this.LFork1Philo;
        forkImages[1] = this.RFork1Philo;
        forkImages[2] = this.LFork2Philo;
        forkImages[3] = this.RFork2Philo;
        forkImages[4] = this.LFork3Philo;
        forkImages[5] = this.RFork3Philo;
        forkImages[6] = this.LFork4Philo;
        forkImages[7] = this.RFork4Philo;
        forkImages[8] = this.LFork5Philo;
        forkImages[9] = this.RFork5Philo;
        
        philoActions[0] = this.txtPhilo1;
        philoActions[1] = this.txtPhilo2;
        philoActions[2] = this.txtPhilo3;
        philoActions[3] = this.txtPhilo4;
        philoActions[4] = this.txtPhilo5;
        
        
        
        for(int i = 0; i < philosopher.length; i++) {
            
            JLabel leftFork = forks[i];
            JLabel rightFork = forks[(i + 1) % forks.length];
            
            
            if (i == philosopher.length - 1) {
                
                // The last philosopher picks up the right fork first
                philosopher[i] = new Philosophers(forkClass[i], forkClass[(i + 1) % forks.length], rightFork, leftFork, food, i, thoughts, forkImages, philoActions); 
            } else {
                philosopher[i] = new Philosophers(forkClass[i], forkClass[(i + 1) % forks.length], leftFork, rightFork, food, i, thoughts, forkImages, philoActions);
            }
            
            Thread philo = new Thread(philosopher[i], "Philosopher" + (i + 1));
            philo.start();
            
        }
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtPhilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhilo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhilo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhilosophersVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhilosophersVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhilosophersVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhilosophersVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhilosophersVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Food1;
    private javax.swing.JLabel Food2;
    private javax.swing.JLabel Food3;
    private javax.swing.JLabel Food4;
    private javax.swing.JLabel Food5;
    private javax.swing.JLabel Fork1;
    private javax.swing.JLabel Fork2;
    private javax.swing.JLabel Fork3;
    private javax.swing.JLabel Fork4;
    private javax.swing.JLabel Fork5;
    private javax.swing.JLabel LFork1Philo;
    private javax.swing.JLabel LFork2Philo;
    private javax.swing.JLabel LFork3Philo;
    private javax.swing.JLabel LFork4Philo;
    private javax.swing.JLabel LFork5Philo;
    private javax.swing.JLabel RFork1Philo;
    private javax.swing.JLabel RFork2Philo;
    private javax.swing.JLabel RFork3Philo;
    private javax.swing.JLabel RFork4Philo;
    private javax.swing.JLabel RFork5Philo;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel philo1;
    private javax.swing.JLabel philo2;
    private javax.swing.JLabel philo3;
    private javax.swing.JLabel philo4;
    private javax.swing.JLabel philo5;
    private javax.swing.JLabel philoT1;
    private javax.swing.JLabel philoT2;
    private javax.swing.JLabel philoT3;
    private javax.swing.JLabel philoT4;
    private javax.swing.JLabel philoT5;
    private javax.swing.JTextField txtPhilo1;
    private javax.swing.JTextField txtPhilo2;
    private javax.swing.JTextField txtPhilo3;
    private javax.swing.JTextField txtPhilo4;
    private javax.swing.JTextField txtPhilo5;
    // End of variables declaration//GEN-END:variables
}
